[project]
name = "todo-app"
version = "0.1.0"
description = "Веб-приложение для управления задачами с регистрацией пользователей"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.16.5",
    "python-dotenv>=1.0.0",
    "flask>=3.1.2",
    "sqlalchemy>=2.0.0",
]
